### ISSUE TITLE
Pretrained Weights

### ISSUE THREAD

**Issue by Taha-Bahadori** [learningtitans/isic2018-part3#1]
Do you make the pretrained PyTorch model available like the 2017 challenge?

**Comment by dreavjr** [comment]
We would have to find a place to host the very large files, but yes, we might be able to do it — I _believe_ I still have a backup of everything, including the weights, but I have to check it.

**Comment by Taha-Bahadori** [comment]
@dreavjr It would be really great!

**Comment by Taha-Bahadori** [comment]
@dreavjr This place seems to be a nice place to host a model: https://pytorch.org/hub/

**Comment by ahmadmughees** [comment]
Hi @dreavjr 
Any update to this?
Thanks.

**Comment by dreavjr** [comment]
After looking everywhere, I found out that we have kept the prediction output, but unfortunately not the (very large) model weights for the pretrained models in the 2018 challenge. I'm closing this.
